name = "mxs-myid"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-03-04"
pages_build_output_dir = "./dist"

kv_namespaces = [
	{ binding = "MfaStatus", id = "52c4f6065c8846c89ab71cb40419e342" },
	{ binding = "LogtoAccessToken", id = "ca2385bd7474479cb34d8e661e9c6194" },
	{ binding = "UsernameChangeTimelimit", id = "102d5b07a70543f193e11f8bd42d8dfd" }
]

[placement]
mode = "smart"
