name = "dashboard-functions-dev"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-03-04"
pages_build_output_dir = "./dist"

kv_namespaces = [
	{ binding = "MFARequiredTokens", id = "305251b3e929457fadad216a3fe20f36" },
	{ binding = "LogtoAccessToken", id = "317e47e4c54c460da74f8d7755e6beee" },
	{ binding = "UsernameChangeTimelimit", id = "72523871c5484c7683abdd7b6d39c04d" }
]

[vars]
AVATAR_API = "https://check.mxs.app"
CORS = "https://dashboard-functions-dev.pages.dev"
LOGTO_DOMAIN = "https://id.mxs.app"
LOGTO_DEFAULT_RESOURCE = "https://default.logto.app/api"
ENABLE_NSFW_CHECK = 1
VITE_API_WORKER_ENDPOINT = "https://api.id.mxs.app"
VITE_LEGAL_URL = "https://cookiesandyou.com"
VITE_LOGTO_APPID = "yw2r46h73tzfk8z4bo1go"
VITE_LOGTO_CORE_RESOURCE = "https://default.logto.app/api"
VITE_LOGTO_ENDPOINT = "https://id.mxs.app/"
VITE_LOGTO_RESOURCES = '["https://default.logto.app/api", "https://myaccount.mxs.app"]'
VITE_MATOMO_ENDPOINT = "https://insights.vee.city"
VITE_MATOMO_SITE_ID = 2
VITE_ROOT = "https://dashboard-functions-dev.pages.dev"
VITE_SUPPORT_EMAIL = "support@mxs.email"

[placement]
mode = "smart"
