name = "logto-account-dashboard"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-03-04"
pages_build_output_dir = "./dist"

kv_namespaces = [
	{ binding = "MfaStatus", id = "" },
	{ binding = "LogtoAccessToken", id = "" },
	{ binding = "UsernameChangeTimelimit", id = "" }
]

[vars]
### WEB CLIENT VARIABLES
## All the required logto values
# the url of your logto service. if you are using logto cloud it may look like https://[your_tenant].logto.app
VITE_LOGTO_ENDPOINT = Requried
# the appid of your CLIENT SPA application
VITE_LOGTO_APPID = Requried
# the logto core resource, do not change <= this is only temporary
VITE_LOGTO_CORE_RESOURCE = https://default.logto.app/api
# the resources the user should have access to use the dashboard. Should be in array format. e.g: '["https://default.logto.app/api", "https://myresouce.logto.app"]'
VITE_LOGTO_RESOURCES = '["https://default.logto.app/api"]' # <= do not change (temporary)

## Extra endpoints
# the url that the dashboard is served from
VITE_ROOT = Required
# the endpoint of a matomo installation. if omitted matomo tracking will be disabled
VITE_MATOMO_ENDPOINT = Optional
VITE_MATOMO_SITE_ID = Optional

## Extra customisable options
# the email in the footer of the dashboard
VITE_SUPPORT_EMAIL = Requried
# the url that users can visit to view the privacy policy/terms of service of your brand. needs to be a full url
VITE_LEGAL_URL = Requried

### WORKER VARIABLES
## Required Logto values
# THESE SHOULD NOT BE SET IN THE WRANGLER.TOML!!
# Please set these values using the wrangler cli: https://developers.cloudflare.com/workers/wrangler/commands/#secret
LOGTO_APP_ID = Required - Set via wrangler cli!
LOGTO_APP_SECRET = Required - Set via wrangler cli!
# the url of your logto service. if you are using logto cloud it may look like https://[your_tenant].logto.app
LOGTO_DOMAIN = "https://id.mxs.app"
# the default resource of your logto application. If you are on a self hosted instance it will be "https://default.logto.app/api", if you are using logto cloud it will look someting like "https://v12345.logto.app/api"
LOGTO_DEFAULT_RESOURCE = "https://default.logto.app/api"

# settings for avatar nsfw checking. use in conjunction with https://github.com/t2vee/nsfwjs-avatar-service
AVATAR_API = ""
ENABLE_NSFW_CHECK = 1

[placement]
mode = "smart"
