name = "myid"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-09-23"
pages_build_output_dir = "./dist"

kv_namespaces = [
	{ binding = "MfaStatus", id = "c201a30ed44745ad8243bfb845a2f5c5" },
	{ binding = "LogtoAccessToken", id = "5dbff618404840619858666eb68e8343" },
	{ binding = "UsernameChangeTimelimit", id = "6b748246668a4769b68eaa1972bb7c85" }
]

[vars]
### WEB CLIENT VARIABLES
## All the required logto values
# the url of your logto service. if you are using logto cloud it may look like https://[your_tenant].logto.app
VITE_LOGTO_ENDPOINT = "https://login.eri.osaka/"
# the appid of your CLIENT SPA application
VITE_LOGTO_APPID = "9a2avn1glhmprcwyilv52"
# the logto core resource, do not change <= this is only temporary
VITE_LOGTO_CORE_RESOURCE = "https://default.logto.app/api"
# the resources the user should have access to use the dashboard. Should be in array format. e.g: '["https://default.logto.app/api", "https://myresouce.logto.app"]'
VITE_LOGTO_RESOURCES = '["https://default.logto.app/api"]' # <= do not change (temporary)

## Extra endpoints
# the url that the dashboard is served from
VITE_ROOT = "https://myid.eri.osaka"
# the endpoint of a matomo installation. if omitted matomo tracking will be disabled
# VITE_MATOMO_ENDPOINT = Optional
# VITE_MATOMO_SITE_ID = Optional

## Extra customisable options
# the email in the footer of the dashboard
VITE_SUPPORT_EMAIL = "i@i.cn"
# the url that users can visit to view the privacy policy/terms of service of your brand. needs to be a full url
VITE_LEGAL_URL = "https://github.com/EriTang"

### WORKER VARIABLES
## Required Logto values
# the url of your logto service. if you are using logto cloud it may look like https://[your_tenant].logto.app
LOGTO_DOMAIN = "https://login.eri.osaka/"
# the default resource of your logto application. If you are on a self hosted instance it will be "https://default.logto.app/api", if you are using logto cloud it will look someting like "https://v12345.logto.app/api"
LOGTO_DEFAULT_RESOURCE = "https://default.logto.app/api"

# settings for avatar nsfw checking. use in conjunction with https://github.com/t2vee/nsfwjs-avatar-service
AVATAR_API = ""
ENABLE_NSFW_CHECK = 0

[placement]
mode = "smart"
