name = "mxs-account-worker"
main = "src/index.js"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-03-04"
workers_dev = false
minify = true

kv_namespaces = [
	{ binding = "MFARequiredTokens", id = "305251b3e929457fadad216a3fe20f36" },
	{ binding = "LogtoAccessToken", id = "317e47e4c54c460da74f8d7755e6beee" },
	{ binding = "UsernameChangeTimelimit", id = "72523871c5484c7683abdd7b6d39c04d" }
]

[vars]
AVATAR_API = "https://check.mxs.app"
CORS = "https://myid.mxs.app"
ISSUER = "https://id.mxs.app/oidc"
JWKS_URI = "https://id.mxs.app/oidc/jwks"
LOGTO_DOMAIN = "https://id.mxs.app"

[placement]
mode = "smart"
