name = "mxs-myid"
type = "javascript"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-03-04"

kv_namespaces = [
	{ binding = "MFARequiredTokens", id = "305251b3e929457fadad216a3fe20f36" },
	{ binding = "LogtoAccessToken", id = "317e47e4c54c460da74f8d7755e6beee" },
	{ binding = "UsernameChangeTimelimit", id = "72523871c5484c7683abdd7b6d39c04d" }
]

[vars]
AVATAR_API = "https://check.mxs.app"
CORS = "https://myid.mxs.app"
LOGTO_DOMAIN = "https://id.mxs.app"
LOGTO_DEFAULT_RESOURCE = "https://default.logto.app/api"
ENABLE_NSFW_CHECK = 1

[site]
bucket = "./dist"
entry-point = "./functions"

[[build.upload]]
format = "modules"
directory = "./dist"

[[build.upload.include]]
pattern = "dist/**"

[placement]
mode = "smart"
